# Generated by Django 4.1 on 2023-08-16 00:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("marketplace", "0004_alter_tax_tax_slug"),
    ]

    operations = [
        migrations.RemoveField(model_name="tax", name="tax_slug",),
    ]
