# Generated by Django 4.1 on 2023-07-29 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_alter_user_role"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user", old_name="is_superuser", new_name="is_superadmin",
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.PositiveSmallIntegerField(
                blank=True, choices=[(2, "Customer"), (1, "Vendor")], null=True
            ),
        ),
    ]
