# Generated by Django 4.1 on 2023-08-11 23:47

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0014_alter_user_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="location",
            field=django.contrib.gis.db.models.fields.PointField(
                blank=True, null=True, srid=4326
            ),
        ),
    ]
