# Generated by Django 4.1 on 2023-08-03 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("menu", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name": "category", "verbose_name_plural": "categories"},
        ),
        migrations.AlterField(
            model_name="category",
            name="description",
            field=models.TextField(blank=True, max_length=250),
        ),
    ]
