# Generated by Django 4.1 on 2023-08-03 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("menu", "0002_alter_category_options_alter_category_description"),
    ]

    operations = [
        migrations.RenameField(
            model_name="category", old_name="modified_at", new_name="updated_at",
        ),
    ]
