# Generated by Django 4.1 on 2023-08-03 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("menu", "0004_rename_modified_at_fooditem_updated_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fooditem",
            name="description",
            field=models.TextField(blank=True, max_length=250),
        ),
    ]
