# Generated by Django 4.1 on 2023-08-20 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="payment_method",
            field=models.CharField(choices=[("PayPal", "RazorPay")], max_length=100),
        ),
    ]
