# Generated by Django 4.1 on 2023-08-20 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0002_alter_payment_payment_method"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="payment_method",
            field=models.CharField(
                choices=[("PayPal", "PayPal"), ("RazorPay", "RazorPay")], max_length=100
            ),
        ),
    ]
